# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
