# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 22:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_creator', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_opponent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChosenPokemons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle', to='battles.Battle')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_first_pokemon', to='pokemons.Pokemon')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_second_pokemon', to='pokemons.Pokemon')),
                ('third', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_third_pokemon', to='pokemons.Pokemon')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_chose', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
