# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 05:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battles', '0003_auto_20180316_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(choices=[(1, 1), (2, 2), (3, 3)], max_length=1)),
                ('battle_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_pokemons', to='battles.Battle')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='pokemons.Pokemon')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='BattleTeams',
            name='battle_related',
        ),
        migrations.RemoveField(
            model_name='BattleTeams',
            name='first',
        ),
        migrations.RemoveField(
            model_name='BattleTeams',
            name='second',
        ),
        migrations.RemoveField(
            model_name='BattleTeams',
            name='third',
        ),
        migrations.RemoveField(
            model_name='BattleTeams',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='BattleTeams',
        ),
    ]
