# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0006_auto_20180316_0622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chosenpokemon',
            options={'ordering': ['order']},
        ),
    ]
