# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0007_auto_20180316_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chosenpokemon',
            name='order',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1),
        ),
    ]
