# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0004_pokemon_sprite'),
        ('battles', '0008_auto_20180318_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chosenpokemon',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='chosenpokemon',
            name='pokemons',
            field=models.ManyToManyField(related_name='pokemons', to='pokemons.Pokemon'),
        ),
    ]
