# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 04:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battles', '0009_auto_20180321_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
