# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0010_battle_winner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battleteam',
            options={'ordering': ['battle_related']},
        ),
        migrations.RemoveField(
            model_name='battleteam',
            name='order',
        ),
    ]
