# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0011_auto_20180326_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleteam',
            name='pokemons',
            field=models.ManyToManyField(related_name='battle_team', to='pokemons.Pokemon'),
        ),
    ]
