# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0012_auto_20180330_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('O', 'Ongoing'), ('F', 'Finished')], default='O', max_length=2),
        ),
    ]
