# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0014_auto_20180514_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_opponent', to=settings.AUTH_USER_MODEL),
        ),
    ]
