# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0017_auto_20180514_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='key',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Invitation key'),
        ),
    ]
