# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0020_invite_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='accepted',
        ),
    ]
