# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0022_invite_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='accepted',
            field=models.NullBooleanField(verbose_name='User has accepted this invite'),
        ),
    ]
