# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0023_auto_20180522_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='User has accepted this invite'),
        ),
    ]
