# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0024_auto_20180522_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('O', 'Ongoing'), ('F', 'Finished'), ('P', 'Processing')], default='O', max_length=2),
        ),
    ]
