# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0025_auto_20180523_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
