# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0026_auto_20180528_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleteam',
            name='battle_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='battles.Battle'),
        ),
    ]
