# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0028_auto_20180614_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleteam',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
