# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name="Pokemon's ID")),
                ('name', models.CharField(max_length=60, verbose_name="Pokemon's name")),
                ('attack', models.SmallIntegerField(verbose_name='Attack')),
                ('defense', models.SmallIntegerField(verbose_name='Defense')),
                ('hp', models.SmallIntegerField(verbose_name='HP')),
            ],
        ),
    ]
