# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='_id',
            field=models.SmallIntegerField(default=0, unique=True, verbose_name="Pokemon's ID"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
